# Upstream git repository
remote = "github.com/relnod/dotm"

# Path to local git repository
path = ".dotfiles/"

# Configs to be included
include = [
    "bash",
    "nvim",
    "tmux"
]

# Configs to be excluded
exclude = [
    "bash",
    "nvim",
    "tmux"
]
