version: 2
jobs:
  verify:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run:
          command: |
            sudo apt install rsync
            GO111MODULE=off go get github.com/petergtz/pegomock/pegomock
            GO111MODULE=off go get golang.org/x/tools/cmd/goimports
            GO111MODULE=off go get golang.org/x/lint/golint
            make verify
  test:
    docker:
      - image: circleci/golang:1.11.1
        environment:
          USER: circleci
          SKIP_TEST_DOCKER: "volumes don't work in circleci (docker in docker)"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make test
workflows:
  version: 2
  verify_and_test:
    jobs:
      - verify
      - test
