version: 2
jobs:

  #
  # Job: verify
  #
  verify:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run:
          command: |
            sudo apt install rsync
            GO111MODULE=off go get github.com/petergtz/pegomock/pegomock
            GO111MODULE=off go get golang.org/x/tools/cmd/goimports
            GO111MODULE=off go get golang.org/x/lint/golint
            make verify

  #
  # Job: test
  #
  test:
    docker:
      - image: circleci/golang:1.11.1
        environment:
          USER: circleci
          SKIP_TEST_DOCKER: "volumes don't work in circleci (docker in docker)"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make test

  #
  # Job: coverage
  #
  coverage:
    docker:
      - image: circleci/golang:1.11.1
        environment:
          USER: circleci
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            GO111MODULE=off go get github.com/wadey/gocovmerge
            make coverage
            bash <(curl -s https://codecov.io/bash)

  #
  # Job: push-latest-image-to-dockerhub
  #
  push-latest-image-to-dockerhub:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make push-docker

  #
  # Job: version
  #
  version:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run:
          command: |
            make build
            VERSION=$(./build/dotm --version | grep -oP "v\K(\d+\.\d+\.\d+)")
            mkdir -p /tmp/version
            echo ${VERSION} > /tmp/version/VERSION
      - persist_to_workspace:
          root: /tmp/version
          paths: VERSION

  #
  # Job: push-release-image-to-dockerhub
  #
  push-release-image-to-dockerhub:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/version
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            cat /tmp/version/VERSION
            TAG=$(cat /tmp/version/VERSION) make push-docker

  #
  # Job: publish-github-release
  #
  publish-github-release:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/version
      - run:
          command: |
            GO111MODULE=off go get github.com/tcnksm/ghr
            VERSION=v$(cat /tmp/version/VERSION) COMMIT=${CIRCLE_SHA1} make release

workflows:
  version: 2
  test_verify:
    jobs:
      - verify
      - test
      - coverage:
          requires:
            - test
            - verify
      - push-latest-image-to-dockerhub:
          requires:
            - test
            - verify
          filters:
            branches:
              only: master

  release:
    jobs:
      - version:
         filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - approve:
          type: approval
          requires:
            - version
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - push-release-image-to-dockerhub:
          requires:
            - approve
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - approve
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
